import type { SectionType, TemplateId } from '../../types/cv';

export type TemplateFamily = 'sidebar' | 'split' | 'single' | 'band';
export type SectionHeadingStyle = 'rule' | 'pill' | 'bar' | 'label';
export type ContactStyle = 'stack' | 'inline' | 'pills';
export type EntryStyle = 'timeline' | 'card' | 'plain' | 'bordered';
export type SkillStyle = 'bars' | 'chips' | 'list' | 'inline' | 'dots' | 'sarif';
export type LanguageStyle = 'bars' | 'cefr' | 'words' | 'dots';
export type SummaryStyle = 'plain' | 'card' | 'quote';
export type ThumbLayout = 'sidebar' | 'split' | 'single' | 'band';

export interface TemplateTheme {
  family: TemplateFamily;
  thumbLayout: ThumbLayout;
  sidebarPosition?: 'left' | 'right';
  fontFamily: string;
  page: string;
  text: string;
  muted: string;
  line: string;
  accent: string;
  accentAlt: string;
  accentSoft: string;
  accentDark: string;
  sidebarBg?: string;
  sidebarText?: string;
  headerBg?: string;
  headerText?: string;
  headerAlign: 'left' | 'center';
  sectionHeading: SectionHeadingStyle;
  contactStyle: ContactStyle;
  entryStyle: EntryStyle;
  skillStyle: SkillStyle;
  languageStyle: LanguageStyle;
  summaryStyle: SummaryStyle;
  sidebarSections: SectionType[];
  uppercaseName?: boolean;
  nameLetterSpacing?: string;
}

export const TEMPLATE_THEMES: Record<TemplateId, TemplateTheme> = {
  modern: {
    family: 'sidebar',
    thumbLayout: 'sidebar',
    sidebarPosition: 'left',
    fontFamily: "'Arial', 'Segoe UI', sans-serif",
    page: '#ffffff',
    text: '#1a1a2e',
    muted: '#667085',
    line: '#e8dcfb',
    accent: '#5b21b6',
    accentAlt: '#7c3aed',
    accentSoft: '#f5f3ff',
    accentDark: '#4c1d95',
    sidebarBg: 'linear-gradient(180deg, #f5f3ff 0%, #ede9fe 100%)',
    sidebarText: '#2e1065',
    headerAlign: 'left',
    sectionHeading: 'bar',
    contactStyle: 'stack',
    entryStyle: 'timeline',
    skillStyle: 'bars',
    languageStyle: 'bars',
    summaryStyle: 'plain',
    sidebarSections: ['skills', 'languages', 'certifications'],
    uppercaseName: true,
    nameLetterSpacing: '0.12em',
  },
  classic: {
    family: 'single',
    thumbLayout: 'single',
    fontFamily: "'Crimson Pro', Georgia, serif",
    page: '#fffdf8',
    text: '#1e1b18',
    muted: '#6b6157',
    line: '#d8cec2',
    accent: '#5a4a3f',
    accentAlt: '#8a6f5a',
    accentSoft: '#f6efe7',
    accentDark: '#3f342b',
    headerAlign: 'center',
    sectionHeading: 'rule',
    contactStyle: 'inline',
    entryStyle: 'bordered',
    skillStyle: 'list',
    languageStyle: 'words',
    summaryStyle: 'quote',
    sidebarSections: [],
    uppercaseName: true,
    nameLetterSpacing: '0.16em',
  },
  minimal: {
    family: 'single',
    thumbLayout: 'single',
    fontFamily: "'Arial', 'Helvetica Neue', sans-serif",
    page: '#ffffff',
    text: '#202020',
    muted: '#7c7c7c',
    line: '#e9e9e9',
    accent: '#111111',
    accentAlt: '#4b5563',
    accentSoft: '#f5f5f5',
    accentDark: '#0f172a',
    headerAlign: 'left',
    sectionHeading: 'label',
    contactStyle: 'inline',
    entryStyle: 'plain',
    skillStyle: 'inline',
    languageStyle: 'words',
    summaryStyle: 'plain',
    sidebarSections: [],
    uppercaseName: true,
    nameLetterSpacing: '0.18em',
  },
  creative: {
    family: 'split',
    thumbLayout: 'split',
    fontFamily: "'Trebuchet MS', 'Segoe UI', sans-serif",
    page: '#ffffff',
    text: '#201a30',
    muted: '#6e6480',
    line: '#eadcf7',
    accent: '#ec4899',
    accentAlt: '#8b5cf6',
    accentSoft: '#fdf2f8',
    accentDark: '#9d174d',
    headerAlign: 'left',
    sectionHeading: 'pill',
    contactStyle: 'pills',
    entryStyle: 'card',
    skillStyle: 'chips',
    languageStyle: 'dots',
    summaryStyle: 'card',
    sidebarSections: ['skills', 'languages'],
    nameLetterSpacing: '-0.03em',
  },
  professional: {
    family: 'band',
    thumbLayout: 'band',
    fontFamily: "'Segoe UI', Arial, sans-serif",
    page: '#ffffff',
    text: '#1d2433',
    muted: '#64748b',
    line: '#dbe3ee',
    accent: '#1e3a5f',
    accentAlt: '#2d5a8a',
    accentSoft: '#eef4fb',
    accentDark: '#132a42',
    headerBg: 'linear-gradient(135deg, #1e3a5f, #2d5a8a)',
    headerText: '#ffffff',
    headerAlign: 'left',
    sectionHeading: 'bar',
    contactStyle: 'inline',
    entryStyle: 'bordered',
    skillStyle: 'chips',
    languageStyle: 'words',
    summaryStyle: 'plain',
    sidebarSections: ['skills', 'languages'],
  },
  executive: {
    family: 'band',
    thumbLayout: 'band',
    fontFamily: "'Arial', 'Segoe UI', sans-serif",
    page: '#fffefc',
    text: '#1e1d1a',
    muted: '#6d665f',
    line: '#e5ddd2',
    accent: '#8b6a3d',
    accentAlt: '#1f2937',
    accentSoft: '#f6f0e6',
    accentDark: '#2b241c',
    headerBg: 'linear-gradient(135deg, #1f2937, #374151)',
    headerText: '#fef3c7',
    headerAlign: 'left',
    sectionHeading: 'pill',
    contactStyle: 'inline',
    entryStyle: 'card',
    skillStyle: 'dots',
    languageStyle: 'words',
    summaryStyle: 'quote',
    sidebarSections: ['skills', 'languages', 'certifications'],
  },
  slate: {
    family: 'sidebar',
    thumbLayout: 'sidebar',
    sidebarPosition: 'right',
    fontFamily: "'Arial', 'Segoe UI', sans-serif",
    page: '#ffffff',
    text: '#1f2937',
    muted: '#64748b',
    line: '#d6dde7',
    accent: '#2563eb',
    accentAlt: '#334155',
    accentSoft: '#eff6ff',
    accentDark: '#1e293b',
    sidebarBg: 'linear-gradient(180deg, #0f172a, #1e293b 52%, #334155)',
    sidebarText: '#f8fafc',
    headerAlign: 'left',
    sectionHeading: 'rule',
    contactStyle: 'stack',
    entryStyle: 'bordered',
    skillStyle: 'chips',
    languageStyle: 'cefr',
    summaryStyle: 'card',
    sidebarSections: ['skills', 'languages'],
  },
  sarif: {
    family: 'sidebar',
    thumbLayout: 'sidebar',
    sidebarPosition: 'left',
    fontFamily: "'Electrolize', 'Arial', sans-serif",
    page: '#ffffff',
    text: '#1f2937',
    muted: '#64748b',
    line: '#d6dde7',
    accent: '#c8a84b',
    accentAlt: '#ffd700',
    accentSoft: 'rgba(200,168,75,0.12)',
    accentDark: '#1e293b',
    sidebarBg: 'linear-gradient(180deg, #0f172a, #1e293b 52%, #334155)',
    sidebarText: '#f8fafc',
    headerAlign: 'left',
    sectionHeading: 'rule',
    contactStyle: 'stack',
    entryStyle: 'bordered',
    skillStyle: 'sarif',
    languageStyle: 'cefr',
    summaryStyle: 'card',
    sidebarSections: ['skills', 'languages'],
  },
  ivory: {
    family: 'single',
    thumbLayout: 'single',
    fontFamily: "'Crimson Pro', Georgia, serif",
    page: '#fffdfa',
    text: '#33261d',
    muted: '#857467',
    line: '#eadfce',
    accent: '#a16207',
    accentAlt: '#7c2d12',
    accentSoft: '#fdf7ed',
    accentDark: '#78350f',
    headerAlign: 'center',
    sectionHeading: 'label',
    contactStyle: 'inline',
    entryStyle: 'plain',
    skillStyle: 'dots',
    languageStyle: 'words',
    summaryStyle: 'quote',
    sidebarSections: [],
    nameLetterSpacing: '0.08em',
  },
  summit: {
    family: 'split',
    thumbLayout: 'split',
    fontFamily: "'Arial', 'Segoe UI', sans-serif",
    page: '#ffffff',
    text: '#152033',
    muted: '#64748b',
    line: '#dce6f2',
    accent: '#0f8c80',
    accentAlt: '#0ea5e9',
    accentSoft: '#e6fffb',
    accentDark: '#134e4a',
    headerAlign: 'left',
    sectionHeading: 'bar',
    contactStyle: 'pills',
    entryStyle: 'timeline',
    skillStyle: 'bars',
    languageStyle: 'bars',
    summaryStyle: 'card',
    sidebarSections: ['skills', 'languages', 'certifications'],
  },
  studio: {
    family: 'split',
    thumbLayout: 'split',
    fontFamily: "'Arial', 'Segoe UI', sans-serif",
    page: '#ffffff',
    text: '#1f1a24',
    muted: '#756a80',
    line: '#ecdff2',
    accent: '#db2777',
    accentAlt: '#7c3aed',
    accentSoft: '#fdf2f8',
    accentDark: '#831843',
    headerAlign: 'left',
    sectionHeading: 'pill',
    contactStyle: 'pills',
    entryStyle: 'card',
    skillStyle: 'chips',
    languageStyle: 'cefr',
    summaryStyle: 'card',
    sidebarSections: ['skills', 'languages', 'projects'],
  },
  atlas: {
    family: 'sidebar',
    thumbLayout: 'sidebar',
    sidebarPosition: 'left',
    fontFamily: "'Arial', 'Segoe UI', sans-serif",
    page: '#ffffff',
    text: '#1d2939',
    muted: '#667085',
    line: '#d9e4ea',
    accent: '#0f766e',
    accentAlt: '#14b8a6',
    accentSoft: '#f0fdfa',
    accentDark: '#134e4a',
    sidebarBg: 'linear-gradient(180deg, #0f766e, #115e59)',
    sidebarText: '#f0fdfa',
    headerAlign: 'left',
    sectionHeading: 'rule',
    contactStyle: 'stack',
    entryStyle: 'card',
    skillStyle: 'bars',
    languageStyle: 'cefr',
    summaryStyle: 'plain',
    sidebarSections: ['skills', 'languages', 'certifications'],
    uppercaseName: true,
    nameLetterSpacing: '0.06em',
  },
  dossier: {
    family: 'single',
    thumbLayout: 'single',
    fontFamily: "'Arial', 'Segoe UI', sans-serif",
    page: '#ffffff',
    text: '#111827',
    muted: '#6b7280',
    line: '#d1d5db',
    accent: '#111827',
    accentAlt: '#374151',
    accentSoft: '#f3f4f6',
    accentDark: '#0f172a',
    headerAlign: 'left',
    sectionHeading: 'rule',
    contactStyle: 'inline',
    entryStyle: 'bordered',
    skillStyle: 'dots',
    languageStyle: 'cefr',
    summaryStyle: 'plain',
    sidebarSections: [],
  },
  north: {
    family: 'split',
    thumbLayout: 'split',
    fontFamily: "'Arial', 'Segoe UI', sans-serif",
    page: '#fbfdff',
    text: '#0f172a',
    muted: '#64748b',
    line: '#d8e4ef',
    accent: '#2563eb',
    accentAlt: '#0ea5e9',
    accentSoft: '#eff6ff',
    accentDark: '#1d4ed8',
    headerAlign: 'left',
    sectionHeading: 'label',
    contactStyle: 'inline',
    entryStyle: 'plain',
    skillStyle: 'bars',
    languageStyle: 'dots',
    summaryStyle: 'plain',
    sidebarSections: ['skills', 'languages'],
    uppercaseName: true,
    nameLetterSpacing: '0.08em',
  },
  zenith: {
    family: 'band',
    thumbLayout: 'band',
    fontFamily: "'Arial', 'Segoe UI', sans-serif",
    page: '#ffffff',
    text: '#141722',
    muted: '#6b7280',
    line: '#d7dce5',
    accent: '#111827',
    accentAlt: '#7c3aed',
    accentSoft: '#f5f3ff',
    accentDark: '#030712',
    headerBg: 'linear-gradient(135deg, #111827, #312e81)',
    headerText: '#f8fafc',
    headerAlign: 'left',
    sectionHeading: 'bar',
    contactStyle: 'pills',
    entryStyle: 'timeline',
    skillStyle: 'chips',
    languageStyle: 'bars',
    summaryStyle: 'quote',
    sidebarSections: ['skills', 'languages', 'projects'],
    uppercaseName: true,
    nameLetterSpacing: '0.08em',
  },
  editorial: {
    family: 'split',
    thumbLayout: 'split',
    fontFamily: "'Crimson Pro', Georgia, serif",
    page: '#fffdfb',
    text: '#231711',
    muted: '#6d584f',
    line: '#decfc3',
    accent: '#9a3412',
    accentAlt: '#d97706',
    accentSoft: '#fff4eb',
    accentDark: '#5f1d0f',
    headerAlign: 'center',
    sectionHeading: 'rule',
    contactStyle: 'inline',
    entryStyle: 'plain',
    skillStyle: 'chips',
    languageStyle: 'words',
    summaryStyle: 'quote',
    sidebarSections: ['skills', 'languages', 'certifications'],
    uppercaseName: true,
    nameLetterSpacing: '0.1em',
  },
};
